# -*- coding: utf-8 -*-
"""Ativ_OpArit_CompL_2021_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19UIOp4-ZthSegoVsfgyRq77h46vbccIk

1- Faça um Programa que mostre a mensagem "Alo mundo" na tela.
"""

'''
Iniciando programacao m Python
Disciplina Computacao L
'''

print("Alo mundo") # meu primeiro codigo

"""2- Faça um Programa que converta metros para centímetros."""

entrada = 13
saida = entrada*100
print(saida)

valor = 13
valor *= 100
print('Convertendo em centímetros, o resultado é:',valor,'cm')

"""3- Faça um Programa que calcule e mostre a área do círculo, criando variáveis para cada medida necessária ao cálculo desejado."""

#Area do circulo = pi*r²
pi = 3.14
r = 5
rr = r*r
area = pi*rr
print('A área o círculo é',area)

"""4- Faça um Programa que calcule a área de um quadrado, em seguida mostre o dobro desta área para o usuário."""

lado = 2
# lado = lado**2
# lado *= lado
# lado = lado*lado*2
areaQuad = lado*lado
dobro = areaQuad*2
print('O resultado é', dobro)

"""5- Faça um Programa que a partir da temperatura em graus Fahrenheit (F), transforme e mostre-a em graus Celsius (C). Sabendo que C = 5 * ((F-32) / 9)."""

tempF = 27
tempC = 5*((tempF-32)/9)
print('A temperatura em graus Celsius é',tempC,'ºC')

"""6- Faça um Programa que a partir da temperatura em graus Celsius, transforme-a e mostre em graus Fahrenheit."""

grausC = 21
grausF = 1.8*grausC+32
print("A temperatura em graus Fahrenheit é",grausF,'ºF')

"""7- Tendo como dado de entrada a altura de uma pessoa, construa um algoritmo que calcule seu peso ideal, usando a seguinte fórmula: (72.7*altura) - 58"""

altura = 1.80
pesoIdeal = 72.7*altura-58
print('O peso ideal é',pesoIdeal,'kg')

"""8- Faça um Programa que, a partir de 2 números inteiros e um número real, calcule e mostre:<br>
     a) o produto do dobro do primeiro com metade do segundo.<br>
     b) a soma do triplo do primeiro com o terceiro.<br>
     c) o terceiro elevado ao cubo.
"""

numInt1 = 3
numInt2 = 7
numReal = 5.89

letraA = (2*numInt1)*(numInt2/2)
letraB = (3*numInt1)+(numReal)
letraC = numReal**3

print('Letra a)',letraA)
print('Letra b)',letraB)
print('Letra c)',letraC)