# -*- coding: utf-8 -*-
"""ExercicioProg.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TCSfTSGDor8li54o2djnQmnhSuWI7Zht
"""

# Alo Mundo

print("Alo Mundo")

#convensor de metros em centimetros

metros = float(input("Digite um numero em metros:"))
centimetros = metros*100

print("O resultado da convencao de", metros, "metros eh", centimetros, "centimetros")

#calculando a area do circulo

raio = float(input("Digite o raio do circulo que vc quer calcular a area:"))
pi = 3.14
area = pi* raio**2

print("A area do curculo cujo o raio eh", raio, "eh:", area)

#calculando a area de um quadrado e motrando pro usuario o dobro do resultado

lado = float(input("Digite o lado do quadrado que vc quer calcular a area:"))
resultado = lado*lado
dobro = resultado*2

print("A area do quadrado eh", resultado, ",ja o dobro do valor eh", dobro)

#convencao de Fahrenheit para Celsius 

F = float(input("Digite o valor em Fahrenheit:"))
C = 5 * ((F-32) / 9)

print("A convencao de",F, "Fahrenheit para Celsius eh de",C,"Celsius")

#convencao de Celsius para Fahrenheit

C = float(input("Digite o valor em Celsius:"))
F = ((9*C)/5)+32

print("Aconcencao de",C, "Celsius para Fahrenheit eh de",F, "Fahrenheit")

#calculando o peso ideal

altura = float(input("Qual a sua altura:"))
pIdeal =  (72.7*altura) - 58

print("Seu peso ideal eh de:", pIdeal,"kg")

#calculando a partir de 2 números inteiros e um número real

pInteiro = float(input("Digite o primeiro numero inteiro:"))
sInteiro = float(input("Digite o segundo numero inteiro:"))
nReal = float(input("digite o numero real:"))

resultadoA = (pInteiro*2)*(sInteiro/2)

print("O produto do dobre de", pInteiro, "com metade de", sInteiro, "eh", resultadoA)

resultadoB = (pInteiro*3) + nReal

print("A soma do triplo de", pInteiro, "com", nReal, "eh", resultadoB)
 
resultadoC = nReal **3

print("O", nReal,"elevado ao cubo eh", resultadoC)